### ISSUE TITLE
Interpretation of groundtruth.txt in the synthetic datasets

### ISSUE THREAD

**Issue by kvmanohar22** [tub-rip/ECRot#2]
The `groundtruth.txt` files constain 8 columns. The first column supposedly corresponds to timestamp in seconds. What do the remaining columns represent?

```
0.001 0.706746 -0.321067 0.626692 -0.706753 0.000354 0.000353 0.70746
0.002 0.706746 -0.321067 0.626692 -0.706399 -0.00018 0.001596 0.707812
```

**Comment by Shuang1997** [comment]
Hi, thanks for your interest.
The 8 columns are:  timestamp, x, y, z, qx, qy, qz, qw, 
where (x, y, z) indicates the position and (qx, qy, qz, qw) is a quaternion representing camera orientation.
